services:
  palace-workbench:
    image: ghcr.io/dangione/palace-workbench:dev
    ports:
      - "6080:6080"
      - "5901:5901"
    volumes:
      - ./projects:/projects
    restart: unless-stopped
